capstone 2/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

capstone 2/todolist/urls.py
from django.urls import path
from . import views


app_name = 'todolist'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='todoitem'),
    path('eventitem/<int:eventitem_id>/', views.eventitem, name='eventitem'),
    path('update_profile/<int:user_id>', views.update_profile, name='update_profile'),

    
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),

    
    path('create_task', views.create_task, name="create_task"),
    path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
    path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
    
    
    path('create_event', views.create_event, name="create_event"),
]

capstone 2/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
	
 
 
 
class Event(models.Model):
	event_name = models.CharField(max_length=100)
	event_description = models.CharField(max_length=100)
	event_status = models.CharField(max_length=50, default="pending")
	event_date = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

capstone 2/todolist/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import widgets
from django.contrib.auth.models import User




class Login(forms.Form):
	username = forms.CharField(label="Username", max_length=20)
	password = forms.CharField(label="Password", max_length=20)
 




class Register(forms.Form):
	username = forms.CharField(label="Username", max_length=20)
	first_name = forms.CharField(label="First Name", max_length=20)
	last_name = forms.CharField(label="Last Name", max_length=20)
	email = forms.EmailField(label="Email", max_length=50)
	password = forms.CharField(label="Password", max_length=20)
	con_password = forms.CharField(label="Confirm Password", max_length=20)





class UpdateProfile(forms.ModelForm):
	first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'password']




class AddTask(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class UpdateTask(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=50)
	status = forms.CharField(label='Status', max_length=50)




class AddEvent(forms.Form):
	event_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

capstone 2/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.forms.models import model_to_dict
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.utils import timezone


from .models import ToDoItem, Event 
from .forms import Login, Register, UpdateProfile, AddEvent, AddTask, UpdateTask


def index(request):
	# todoitem_list = ToDoItem.objects.all()
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = Event.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'event_list': event_list,
		'user': request.user
	}
	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem,pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def eventitem(request, eventitem_id):
	eventitem = get_object_or_404(Event,pk=eventitem_id)
	return render(request, "todolist/event_item.html", model_to_dict(eventitem))


def register(request):
	context = {}

	if request.method == 'POST':
		form = Register(request.POST)

		if form.is_valid() == False:
			form = Register()
		else:
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			con_password = form.cleaned_data['con_password']
			hash_pass = make_password(password)
			user = authenticate(username=username, first_name=first_name, last_name=last_name, email=email, password=hash_pass)
			context = {
				"username": username,
				"first_name": first_name,
				"last_name": last_name,
				"email": email,
				"password": hash_pass,
			}
			
			duplicates = User.objects.filter(username=username)	

			if password == con_password:
				if not duplicates:
					User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email, password=hash_pass)
					return redirect("todolist:login")
				else:	
					context = {
						"error": True
					}
			else:
				context = {
					"match": True
				}
	return render(request, "todolist/register.html", context)


#UPDATE PROFILE
@login_required
def update_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = UpdateProfile(request.POST, instance=user)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            password = cleaned_data.get('password')
            if password:
                user.password = make_password(password)
            form.save()
            return redirect('todolist:index')
    else:
        form = UpdateProfile(instance=user)

    context = {
        "user_id": user_id,
        "user": user,
        "form": form
    }
    return render(request, 'todolist/update_profile.html', context)


 
 
#CHANGE PASSWORD
def change_password(request):
	is_user_authenticated = False
	user = authenticate(username="johndoe", password="john1234")
	print(user)
	if user is not None:
		authenticated_user = User.objects.get(username="johndoe")
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True
	context = {
		"is_user_authenticated": is_user_authenticated
	}
	return render(request, "todolist/change_password.html", context)


#LOGIN
def login_view(request):
	context = {}
	if request.method == 'POST':
		form = Login(request.POST)

		if form.is_valid() == False:
			form = Login()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

		if user is not None:
			login(request, user)
			return redirect("todolist:index")

		else:
			context = {
				"error": True
			}

	return render(request, "todolist/login.html", context)




#LOGOUT
def logout_view(request):
	logout(request)
	return redirect("todolist:index")




#TASKS
def create_task(request):
	context = {}
	if request.method == 'POST':
		form = AddTask(request.POST)
		if form.is_valid() == False:
			form = AddTask()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			duplicates = ToDoItem.objects.filter(task_name=task_name)	

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}
	return render(request, "todolist/create_task.html", context)



def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)
	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}
	if request.method == 'POST':
		form = UpdateTask(request.POST)
		if form.is_valid() == False:
			form = UpdateTask()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}
	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")



#EVENT
def create_event(request):
    form = AddEvent(request.POST or None)
    context = {}

    if request.method == 'POST' and form.is_valid():
        event_name = form.cleaned_data['event_name']
        description = form.cleaned_data['description']
        duplicates = Event.objects.filter(event_name=event_name)

        if not duplicates:
            Event.objects.create(
                event_name=event_name,
                event_description=description,
                event_date=timezone.now(),
                user_id=request.user.id
            )
            return redirect("todolist:index")
        else:
            context["error"] = True

    context["form"] = form
    return render(request, "todolist/create_event.html", context)

capstone 2/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>
{% endif %}

capstone 2/todolist/templates/todolist/create_event.html
{% extends 'base.html' %}

{% block title %} Add Event {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add an Event</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate event found</p>
			{% endif %}
			<form action="{% url 'todolist:create_event' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="event_description">Description: </label>
					<textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" required></textarea>
				</div>
				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Event">
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

capstone 2/todolist/templates/todolist/create_task.html
{% extends 'base.html' %}

{% block title %} Add Task {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add a Task</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate task found</p>
			{% endif %}
			<form action="{% url 'todolist:create_task' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" required></textarea>
				</div>
				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

capstone 2/todolist/templates/todolist/event_item.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ event_description }}</p>
	<h3>Status</h3>
	<p>{{ event_status }}</p>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Events</a>
	</button> 
</div>
{% endblock %}

capstone 2/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<h1 class="text-center my-3">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
	<h3 class="text-center mb-3">My Tasks</h3>
		<div class="container">
			<div class="row">
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% if todoitem_list %}
						{% for todoitem in todoitem_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:todoitem' todoitem.id %}" class="text-decoration-none">
								{{ todoitem.task_name }}
							</a>
						</li>
						{% endfor %}
					{% else %}
						<p class="text-center">No tasks have been created.</p>
					{% endif %}
				</ul>
			</div>
		</div>
		<h1></h1>
		<h3 class="text-center mb-3">My Events</h3>
			<div class="row">
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% if event_list %}
						{% for eventitem in event_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:eventitem' eventitem.id %}" class="text-decoration-none">
								{{ eventitem.event_name }}
							</a>
						</li>
					{% endfor %}
					{% else %}
						<p class="text-center">No events have been created.</p>
					{% endif %}
			</ul>
		</div>

	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="login">here</a></p>
	{% endif %}

{% endblock %}

capstone 2/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

capstone 2/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
				<h1 class="text-danger">Duplicated User Found</h1>
				<p class="text-danger">A Duplicate User has been Found! User Creation Unsuccessful</p>
			{% elif match == True %}
				<p class="text-danger">Password doesn't Match</p>
			{% endif %}
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="first_name">First Name: </label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="last_name">Last Name: </label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="email">Email: </label>
					<input class="form-control" id="email" type="email" name="email" value="{{ email }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="con_password">Confirm Password: </label>
					<input class="form-control" id="con_password" type="password" name="con_password" value="{{ con_password }}" maxlength="20" required>
				</div>
				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

capstone 2/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ task_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
	</button> 
</div>
{% endblock %}

capstone 2/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{% block title %} Update Profile {% endblock %}

{% block content %}

{% if user.is_anonymous == False %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Update Profile</h1>
			<form action="{% url 'todolist:update_profile' user_id %}" method="post">	
				{% csrf_token %}
				<div class="mb-3">
					<label for="first_name">First Name: {{ first_name }}</label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="last_name">Last Name: {{ last_name }}</label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>
				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update Profile">
				</div>
			</form>
		</div>
	</div>
</div>
{% endif %}
{% endblock %}

capstone 2/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6  offset-3"><div>
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}
					<div class=mb-3">
						<label for="task_name">Task Name: </label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class=mb-3">
						<label for="description">Description: </label>
						<textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status: </label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input classs="btn btn-success" type="submit" value="Update Task">
					</div>
				</form>
			</div>
		</div>
	</div>


	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}

	
{% endblock %}